version: "3.9"

services:
  backend:
    build:
      context: ../backend
    container_name: pricing-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend/react_dashboard
    container_name: pricing-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ../frontend/react_dashboard:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
